import type { CountryConfig, InterestTag } from '../types';

// Every country with full city + editorial data (110 countries across all continents).
// Centers/zooms derived from country geometry bounding boxes (countries-110m.geojson),
// with a few manual overrides where overseas territories or antimeridian wraparound skewed the bbox.
export const SUPPORTED_COUNTRIES: Record<string, CountryConfig> = {
  // Europe
  'PT': { iso2: 'PT', name: 'Portugal', center: [-8.2, 39.5], zoom: 6.5, citiesFile: 'pt' },
  'IT': { iso2: 'IT', name: 'Italy', center: [12.5, 42.5], zoom: 6.0, citiesFile: 'it' },
  'ES': { iso2: 'ES', name: 'Spain', center: [-3.2, 39.8], zoom: 6, citiesFile: 'es' },
  'FR': { iso2: 'FR', name: 'France', center: [2.5, 46.5], zoom: 5.5, citiesFile: 'fr' },
  'DE': { iso2: 'DE', name: 'Germany', center: [10.5, 51.1], zoom: 6, citiesFile: 'de' },
  'GB': { iso2: 'GB', name: 'United Kingdom', center: [-2.9, 54.3], zoom: 6, citiesFile: 'gb' },
  'IE': { iso2: 'IE', name: 'Ireland', center: [-8.0, 53.4], zoom: 7, citiesFile: 'ie' },
  'NL': { iso2: 'NL', name: 'Netherlands', center: [5.2, 52.2], zoom: 7, citiesFile: 'nl' },
  'BE': { iso2: 'BE', name: 'Belgium', center: [4.3, 50.5], zoom: 7, citiesFile: 'be' },
  'CH': { iso2: 'CH', name: 'Switzerland', center: [8.2, 46.8], zoom: 7, citiesFile: 'ch' },
  'AT': { iso2: 'AT', name: 'Austria', center: [13.2, 47.7], zoom: 7, citiesFile: 'at' },
  'DK': { iso2: 'DK', name: 'Denmark', center: [10.4, 56.3], zoom: 7, citiesFile: 'dk' },
  'SE': { iso2: 'SE', name: 'Sweden', center: [17.5, 62.2], zoom: 6, citiesFile: 'se' },
  'NO': { iso2: 'NO', name: 'Norway', center: [18.1, 69.4], zoom: 5.5, citiesFile: 'no' },
  'IS': { iso2: 'IS', name: 'Iceland', center: [-19.0, 65.0], zoom: 6, citiesFile: 'is' },
  'PL': { iso2: 'PL', name: 'Poland', center: [19.1, 51.9], zoom: 6, citiesFile: 'pl' },
  'CZ': { iso2: 'CZ', name: 'Czechia', center: [15.5, 49.8], zoom: 7, citiesFile: 'cz' },
  'HU': { iso2: 'HU', name: 'Hungary', center: [19.5, 47.2], zoom: 7, citiesFile: 'hu' },
  'HR': { iso2: 'HR', name: 'Croatia', center: [16.5, 44.5], zoom: 7, citiesFile: 'hr' },
  'GR': { iso2: 'GR', name: 'Greece', center: [23.4, 38.4], zoom: 7, citiesFile: 'gr' },
  'GE': { iso2: 'GE', name: 'Georgia', center: [43.3, 42.3], zoom: 7, citiesFile: 'ge' },
  'TR': { iso2: 'TR', name: 'Turkey', center: [35.4, 39.0], zoom: 5.5, citiesFile: 'tr' },
  // Africa
  'MA': { iso2: 'MA', name: 'Morocco', center: [-6.0, 31.8], zoom: 6.0, citiesFile: 'ma' },
  'EG': { iso2: 'EG', name: 'Egypt', center: [30.8, 26.8], zoom: 6, citiesFile: 'eg' },
  'TN': { iso2: 'TN', name: 'Tunisia', center: [9.5, 33.8], zoom: 7, citiesFile: 'tn' },
  'DZ': { iso2: 'DZ', name: 'Algeria', center: [1.7, 28.1], zoom: 5.5, citiesFile: 'dz' },
  'LY': { iso2: 'LY', name: 'Libya', center: [17.2, 26.4], zoom: 5.5, citiesFile: 'ly' },
  'ZA': { iso2: 'ZA', name: 'South Africa', center: [24.6, -28.5], zoom: 5.5, citiesFile: 'za' },
  'KE': { iso2: 'KE', name: 'Kenya', center: [37.9, 0.4], zoom: 6, citiesFile: 'ke' },
  'TZ': { iso2: 'TZ', name: 'Tanzania', center: [34.8, -6.3], zoom: 6, citiesFile: 'tz' },
  'ET': { iso2: 'ET', name: 'Ethiopia', center: [40.4, 9.2], zoom: 6, citiesFile: 'et' },
  'GH': { iso2: 'GH', name: 'Ghana', center: [-1.1, 7.9], zoom: 7, citiesFile: 'gh' },
  'NG': { iso2: 'NG', name: 'Nigeria', center: [8.6, 9.1], zoom: 6, citiesFile: 'ng' },
  'SN': { iso2: 'SN', name: 'Senegal', center: [-14.5, 14.5], zoom: 7, citiesFile: 'sn' },
  'CI': { iso2: 'CI', name: 'Côte d\'Ivoire', center: [-5.6, 7.4], zoom: 7, citiesFile: 'ci' },
  'CM': { iso2: 'CM', name: 'Cameroon', center: [12.3, 7.3], zoom: 6, citiesFile: 'cm' },
  'UG': { iso2: 'UG', name: 'Uganda', center: [32.3, 1.4], zoom: 7, citiesFile: 'ug' },
  'RW': { iso2: 'RW', name: 'Rwanda', center: [29.9, -2.0], zoom: 8, citiesFile: 'rw' },
  'ZM': { iso2: 'ZM', name: 'Zambia', center: [27.7, -13.1], zoom: 6, citiesFile: 'zm' },
  'ZW': { iso2: 'ZW', name: 'Zimbabwe', center: [29.1, -18.9], zoom: 7, citiesFile: 'zw' },
  'BW': { iso2: 'BW', name: 'Botswana', center: [24.7, -22.2], zoom: 6, citiesFile: 'bw' },
  'NA': { iso2: 'NA', name: 'Namibia', center: [18.4, -23.0], zoom: 6, citiesFile: 'na' },
  'MZ': { iso2: 'MZ', name: 'Mozambique', center: [35.5, -18.5], zoom: 5.5, citiesFile: 'mz' },
  'MG': { iso2: 'MG', name: 'Madagascar', center: [46.9, -18.8], zoom: 6, citiesFile: 'mg' },
  'MW': { iso2: 'MW', name: 'Malawi', center: [34.2, -13.0], zoom: 7, citiesFile: 'mw' },
  'AO': { iso2: 'AO', name: 'Angola', center: [17.9, -11.2], zoom: 6, citiesFile: 'ao' },
  'CD': { iso2: 'CD', name: 'DR Congo', center: [21.7, -4.0], zoom: 5.5, citiesFile: 'cd' },
  'CG': { iso2: 'CG', name: 'Republic of Congo', center: [14.8, -0.7], zoom: 6, citiesFile: 'cg' },
  'CF': { iso2: 'CF', name: 'Central African Republic', center: [20.9, 6.7], zoom: 6, citiesFile: 'cf' },
  'GA': { iso2: 'GA', name: 'Gabon', center: [11.6, -0.8], zoom: 7, citiesFile: 'ga' },
  'BF': { iso2: 'BF', name: 'Burkina Faso', center: [-1.6, 12.4], zoom: 7, citiesFile: 'bf' },
  'ML': { iso2: 'ML', name: 'Mali', center: [-4.0, 17.5], zoom: 5.5, citiesFile: 'ml' },
  'NE': { iso2: 'NE', name: 'Niger', center: [8.1, 17.6], zoom: 5.5, citiesFile: 'ne' },
  'TD': { iso2: 'TD', name: 'Chad', center: [18.7, 15.4], zoom: 5.5, citiesFile: 'td' },
  'SD': { iso2: 'SD', name: 'Sudan', center: [30.2, 15.1], zoom: 5.5, citiesFile: 'sd' },
  'SS': { iso2: 'SS', name: 'South Sudan', center: [29.6, 7.9], zoom: 6, citiesFile: 'ss' },
  'ER': { iso2: 'ER', name: 'Eritrea', center: [39.7, 15.2], zoom: 7, citiesFile: 'er' },
  'DJ': { iso2: 'DJ', name: 'Djibouti', center: [42.5, 11.8], zoom: 8, citiesFile: 'dj' },
  'SO': { iso2: 'SO', name: 'Somalia', center: [46.1, 5.2], zoom: 6, citiesFile: 'so' },
  'LR': { iso2: 'LR', name: 'Liberia', center: [-9.5, 6.4], zoom: 7, citiesFile: 'lr' },
  'SL': { iso2: 'SL', name: 'Sierra Leone', center: [-11.7, 8.4], zoom: 7, citiesFile: 'sl' },
  'GN': { iso2: 'GN', name: 'Guinea', center: [-11.5, 9.9], zoom: 7, citiesFile: 'gn' },
  'GW': { iso2: 'GW', name: 'Guinea-Bissau', center: [-15.2, 11.8], zoom: 8, citiesFile: 'gw' },
  'GM': { iso2: 'GM', name: 'Gambia', center: [-15.3, 13.5], zoom: 8, citiesFile: 'gm' },
  'BJ': { iso2: 'BJ', name: 'Benin', center: [2.3, 9.2], zoom: 7, citiesFile: 'bj' },
  'TG': { iso2: 'TG', name: 'Togo', center: [0.9, 8.5], zoom: 7, citiesFile: 'tg' },
  'CV': { iso2: 'CV', name: 'Cabo Verde', center: [-23.9, 15.9], zoom: 7.5, citiesFile: 'cv' },
  'KM': { iso2: 'KM', name: 'Comoros', center: [43.8, -11.9], zoom: 7.5, citiesFile: 'km' },
  'MU': { iso2: 'MU', name: 'Mauritius', center: [58.8, -20.1], zoom: 7.5, citiesFile: 'mu' },
  'ST': { iso2: 'ST', name: 'Sao Tome and Principe', center: [7.1, 1.0], zoom: 7.5, citiesFile: 'st' },
  'SZ': { iso2: 'SZ', name: 'Eswatini', center: [31.4, -26.5], zoom: 8, citiesFile: 'sz' },
  'LS': { iso2: 'LS', name: 'Lesotho', center: [28.2, -29.6], zoom: 8, citiesFile: 'ls' },
  'BI': { iso2: 'BI', name: 'Burundi', center: [29.9, -3.4], zoom: 8, citiesFile: 'bi' },
  'GQ': { iso2: 'GQ', name: 'Equatorial Guinea', center: [10.3, 1.6], zoom: 8, citiesFile: 'gq' },
  // Asia
  'JP': { iso2: 'JP', name: 'Japan', center: [137.0, 36.2], zoom: 5.5, citiesFile: 'jp' },
  'KR': { iso2: 'KR', name: 'South Korea', center: [127.5, 36.5], zoom: 7.0, citiesFile: 'kr' },
  'CN': { iso2: 'CN', name: 'China', center: [104.4, 35.8], zoom: 4, citiesFile: 'cn' },
  'CN-TW': { iso2: 'CN-TW', name: 'Taiwan', center: [121.0, 23.6], zoom: 7, citiesFile: 'tw' },
  'TH': { iso2: 'TH', name: 'Thailand', center: [101.0, 13.0], zoom: 5.5, citiesFile: 'th' },
  'VN': { iso2: 'VN', name: 'Vietnam', center: [106.0, 16.5], zoom: 5.5, citiesFile: 'vn' },
  'ID': { iso2: 'ID', name: 'Indonesia', center: [117.0, -2.5], zoom: 4.8, citiesFile: 'id' },
  'IN': { iso2: 'IN', name: 'India', center: [80.0, 22.0], zoom: 4.5, citiesFile: 'in' },
  'KH': { iso2: 'KH', name: 'Cambodia', center: [104.9, 12.5], zoom: 7.0, citiesFile: 'kh' },
  'MM': { iso2: 'MM', name: 'Myanmar', center: [96.7, 19.1], zoom: 5.5, citiesFile: 'mm' },
  'MY': { iso2: 'MY', name: 'Malaysia', center: [109.6, 3.9], zoom: 5.5, citiesFile: 'my' },
  'PH': { iso2: 'PH', name: 'Philippines', center: [121.9, 12.0], zoom: 6, citiesFile: 'ph' },
  'LA': { iso2: 'LA', name: 'Laos', center: [103.8, 18.2], zoom: 6, citiesFile: 'la' },
  'BD': { iso2: 'BD', name: 'Bangladesh', center: [90.4, 23.6], zoom: 7, citiesFile: 'bd' },
  'NP': { iso2: 'NP', name: 'Nepal', center: [84.1, 28.4], zoom: 6, citiesFile: 'np' },
  'LK': { iso2: 'LK', name: 'Sri Lanka', center: [80.7, 7.9], zoom: 7, citiesFile: 'lk' },
  'SG': { iso2: 'SG', name: 'Singapore', center: [103.8, 1.3], zoom: 7.5, citiesFile: 'sg' },
  // Middle East
  'AE': { iso2: 'AE', name: 'United Arab Emirates', center: [54.0, 24.3], zoom: 7, citiesFile: 'ae' },
  'IL': { iso2: 'IL', name: 'Israel', center: [35.1, 31.4], zoom: 7, citiesFile: 'il' },
  'JO': { iso2: 'JO', name: 'Jordan', center: [37.1, 31.3], zoom: 7, citiesFile: 'jo' },
  'OM': { iso2: 'OM', name: 'Oman', center: [55.9, 21.5], zoom: 6, citiesFile: 'om' },
  // North America
  'MX': { iso2: 'MX', name: 'Mexico', center: [-102.0, 23.5], zoom: 5.5, citiesFile: 'mx' },
  'US': { iso2: 'US', name: 'USA', center: [-98.0, 39.5], zoom: 4.0, citiesFile: 'us' },
  'CA': { iso2: 'CA', name: 'Canada', center: [-96.8, 62.5], zoom: 4, citiesFile: 'ca' },
  'CR': { iso2: 'CR', name: 'Costa Rica', center: [-84.0, 10.0], zoom: 7.5, citiesFile: 'cr' },
  'GT': { iso2: 'GT', name: 'Guatemala', center: [-90.2, 15.8], zoom: 7, citiesFile: 'gt' },
  'CU': { iso2: 'CU', name: 'Cuba', center: [-79.6, 21.5], zoom: 6, citiesFile: 'cu' },
  // South America
  'CO': { iso2: 'CO', name: 'Colombia', center: [-74.0, 4.5], zoom: 6.0, citiesFile: 'co' },
  'PE': { iso2: 'PE', name: 'Peru', center: [-76.0, -9.5], zoom: 5.8, citiesFile: 'pe' },
  'AR': { iso2: 'AR', name: 'Argentina', center: [-64.0, -35.0], zoom: 4.5, citiesFile: 'ar' },
  'BR': { iso2: 'BR', name: 'Brazil', center: [-53.0, -14.0], zoom: 4.5, citiesFile: 'br' },
  'BO': { iso2: 'BO', name: 'Bolivia', center: [-63.5, -16.3], zoom: 6, citiesFile: 'bo' },
  'CL': { iso2: 'CL', name: 'Chile', center: [-71.3, -36.6], zoom: 4.5, citiesFile: 'cl' },
  'EC': { iso2: 'EC', name: 'Ecuador', center: [-78.1, -1.8], zoom: 7, citiesFile: 'ec' },
  // Oceania
  'AU': { iso2: 'AU', name: 'Australia', center: [133.5, -27.2], zoom: 4.5, citiesFile: 'au' },
  'NZ': { iso2: 'NZ', name: 'New Zealand', center: [172.5, -40.5], zoom: 6, citiesFile: 'nz' },
  'FJ': { iso2: 'FJ', name: 'Fiji', center: [178.0, -17.7], zoom: 7, citiesFile: 'fj' },
};

export const ALL_TAGS: InterestTag[] = [
  'nature', 'beaches', 'food-wine', 'history', 'shopping', 'nightlife',
];

export const TAG_LABELS: Record<InterestTag, string> = {
  nature:    'Nature',
  beaches:   'Beaches',
  'food-wine': 'Food & Wine',
  history:   'History',
  shopping:  'Shopping',
  nightlife: 'Nightlife',
};

// OpenFreeMap liberty style — no API key required
export const MAP_STYLE = 'https://tiles.openfreemap.org/styles/liberty';

export const GLOBE_ZOOM = 2.5;
export const GLOBE_CENTER: [number, number] = [10, 20];
